### ISSUE TITLE
Purpose of lib

### ISSUE THREAD

**Issue by devth** [ifesdjeen/clj-pushr#3]
Hi, is this meant to be an open source alternative to Pusher? I was looking for a client, but this appears to be an implementation of the server. Thanks.

**Comment by ifesdjeen** [comment]
No, this is not an alternative. This is just an implementation of their protocol, on the server side.

I'm pretty sure there're enough pusher clients around.

**Comment by devth** [comment]
Got it. There's only 1 outdated Clojure partial client.

**Comment by ifesdjeen** [comment]
@devth they've got a java client: https://github.com/pusher/pusher-java-client even though they say it's targeting androind, it should work for everything. Hope that helps :)
